config/urls.py
from django.contrib import admin
from django.urls import path, include

#from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls'))
]

pybo/urls.py
from django.urls import path
from . import views

from .views import detail


app_name = 'pybo'


urlpatterns = [
    path('', views.index, name='index'),
    path('<int:menu_id>/', views.detail, name = 'detail'),
    path('random/', views.random, name='random'),
    path('memo/', views.memo_view, name='memo'),
    path('gia/', views.gia_view, name='gia'),
    path('naver-search/<int:menu_id>/', views.naver_search, name='naver_search'),
    path('random/naver-search/<int:menu_id>/', views.naver_search, name='naver_search'),
    path('create/', views.menu_create, name='menu_create'),]

pybo/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
import datetime
from django.utils import timezone

# Create your models here.

class Menu(models.Model):
    TYPE_CHOICES = [
        ('한식', '한식'),
        ('양식', '양식'),
        ('중식', '중식'),
        ('일식', '일식'),
        ('기타', '기타'),
        ("분식", "분식"),]

    location_CHOICES = [
        ('충정로', '충정로'),
        ('아현동', '아현동'),
        ('풍산빌딩 지하', '풍산빌딩 지하'),
        ('서대문', '서대문'),]

    CONFIRMED_CHOICES = [
        ('Y', '승인됨'),
        ('N', '미승인'),
    ]
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=50, choices = TYPE_CHOICES)
    distance = models.CharField(max_length=50)
    location = models.CharField(max_length=50, choices = location_CHOICES)
    price = models.IntegerField(null=True, blank=True)
    menu_detail = models.CharField(max_length=100, null=True, blank=True)
    confirmed = models.CharField(max_length=2, default = "N")
    def __str__(self):
        return self.name

class Memo(models.Model):
    class Status(models.TextChoices):
        PENDING = '대기중', _('대기중')
        IN_PROGRESS = '진행중', _('진행중')
        COMPLETED = '완료', _('완료')

    title = models.CharField(max_length=100)
    status = models.CharField(
        max_length=10,
        choices=Status.choices,
        default=Status.PENDING,
    )

    def __str__(self):
        return self.title


class ImageURL(models.Model):
    url = models.URLField(max_length=500)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.url

pybo/views.py
# Create your views here.
import urllib.parse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Menu, Memo, ImageURL
from django.db.models import Q
from .form import MenuSearchForm, MenuCreateForm

def naver_search(request, menu_id):
    menu = get_object_or_404(Menu, id=menu_id)
    encoded_query = urllib.parse.quote(f"{menu.name} {menu.location}")
    naver_search_url = f"https://search.naver.com/search.naver?query={encoded_query}"
    return redirect(naver_search_url)


def random(request):
    import random
    form = MenuSearchForm(request.GET)
    random_menu = None

    if form.is_valid():
        type = form.cleaned_data.get('type')
        location = form.cleaned_data.get('location')
        menus = Menu.objects.filter(confirmed='Y')
        if type:
            menus = menus.filter(type=type)
        if location:
            menus = menus.filter(location=location)
        if menus.exists():
            random_menu = random.choice(menus)
            encoded_query = urllib.parse.quote(f"{random_menu.name} {random_menu.location}")
            naver_search_url = f"https://search.naver.com/search.naver?query={encoded_query}"
    context = {
        'form': form,
        'random_menu': random_menu,
        'naver_search_url': naver_search_url
    }

    return render(request, 'pybo/random.html', context)


def index(request):
    kw = request.GET.get('kw', '')  # 검색어
    base_queryset = Menu.objects.filter(confirmed='Y')
    if kw:
        menu_list = base_queryset.filter(
            Q(name__icontains=kw) |  # 이름에 검색어가 포함된 항목
            Q(type__icontains=kw) |  # 타입에 검색어가 포함된
            Q(distance__icontains=kw)|
            Q(menu_detail__icontains=kw)|
            Q(location__icontains=kw)
        ).distinct()  # 중복 제거
    else:
        menu_list = Menu.objects.filter(confirmed='Y')  # 검색어가 없으면 모든 항목 가져오기

    context = {'menu_list': menu_list, 'kw': kw}
    return render(request, 'pybo/menu_list.html', context)

def detail(request,menu_id):
    menu = Menu.objects.get(id=menu_id)
    # menu_list = Menu.objects.all()

    naver_search_url = f"https://search.naver.com/search.naver?query={menu.location} {menu.name}"
    context = {'menu': menu, 'naver_search_url': naver_search_url}

    return render(request, 'pybo/menu_detail.html', context)



def memo_view(request):  # 함수 이름을 memo에서 memo_view로 변경
    memos = Memo.objects.order_by('status') # Memo.objects.all()을 사용하여 모든 Memo 객체 가져오기
    context = {'memos': memos}
    return render(request, 'pybo/memo.html', context)


def gia_view(request):
    image_url = ImageURL.objects.first()
    return render(request, 'pybo/gia.html',{'image_url': image_url})

def menu_create(request):
    if request.method == 'POST':
        form = MenuCreateForm(request.POST)
        if form.is_valid():
            menu = form.save(commit=False)
            menu.save()
            return redirect('pybo:index')
    else:
        form = MenuCreateForm()
    context ={'form':form}
    return render(request, 'pybo/menu_form.html',context)

templates/base.html
{% load static %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-8R1KNY496H"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-8R1KNY496H');
</script>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <head>
<title> 웰컴투충정로 by Nuri v2</title>
</head>


<body>


<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->

</body>

<footer class="footer">
    <div class="container">
        <span class="text-muted">copyright 2024 Nuri all rights reserved</span>
    </div>
</footer>

</html>

templates/pybo/gia.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container mt-4">
    <h1 class="border-bottom py-2">지-하 (지하식당이라는 뜻)</h1>
    <div class="card mt-3">
        <div class="card-body">

            <img src = "{{ image_url }}">

        </div>
    </div>

    <p>
    <div class="d-flex justify-content-start">
        <p class="card-text me-2">
            <a href="{% url 'pybo:index' %}" class="btn btn-secondary">리스트로</a>
        </p>
        <p class="card-text">
            <a href="{% url 'pybo:random' %}" class="btn btn-secondary">그냥 나가서 먹자</a>
        </p>
    </div>




{% endblock %}

templates/pybo/memo.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">

<div class="container mt-4">
    <h1 class="border-bottom py-2">업데이트 계획</h1>
    <div class="card mt-3">
        <div class="card-body">

            <table class="table">
        <thead>
            <tr class="table-dark">
                <th>순번</th>
                <th>내용</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
         {% for item in memos %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{item.title}}</td>
                <td>{{item.status}}</td>


            </tr>
              {% endfor %}
        </tbody>


    </table>

        </div>
    </div>
    <p>
    <p class="card-text"><strong> <a href = "{% url 'pybo:index' %}" class="btn btn-secondary"> 리스트로 </strong></a></p>

</div>
{% endblock %}

templates/pybo/menu_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container mt-4">
    <h1 class="border-bottom py-2">{{ menu.name }}</h1>
    <div class="card mt-3">
        <div class="card-body">
            <p class="card-text"><strong>종류:</strong> {{ menu.type }}</p>
            <p class="card-text"><strong>거리:</strong> {{ menu.distance }}</p>
            <p class="card-text"><strong>위치:</strong> {{ menu.location }}</p>
            <p class="card-text"><strong>가격:</strong> {{ menu.price|intcomma }}원</p>
            <p class="card-text">{{ menu.menu_detail }}</p>
            
            <!-- 네이버 검색 버튼 -->
            <a href="{% url 'pybo:naver_search' menu.id %}" class="btn btn-success mb-3" target="_blank">네이버에서 식당 검색</a>
            
            <p>
            <a href="{% url 'pybo:index' %}" class="btn btn-secondary">리스트로</a>
        </div>
    </div>
</div>
{% endblock %}

templates/pybo/menu_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">메뉴등록 요청</h5>
    <form method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                {% endif %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">{{ error }}</div>
                {% endfor %}
                <p>
            </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">요청하기</button>
    </form>
</div>
{% endblock %}

templates/pybo/menu_list.html
{% extends 'base.html' %}
{% block content %}

{% load humanize %}
{% load static %}

<div class="container my-3">

    <div class="d-flex justify-content-start">
        <p class="card-text me-2">
            <a href="{% url 'pybo:random' %}" class="btn btn-primary">랜덤메뉴추천</a>
        </p>
        <p class="card-text me-2">
            <a href="{% url 'pybo:gia' %}" class="btn btn-primary">지하식당메뉴</a>
        </p>
        <p class="card-text me-2">
        <a href="{% url 'pybo:menu_create' %}" class="btn btn-primary">식당등록해주세요</a>
        </p>

         <p class="card-text">
            <a href="{% url 'pybo:memo' %}" class="btn btn-primary">지금은개발중</a>
        </p>
    </div>

    <div class="row my-3">
        <form action="{% url 'pybo:index' %}" method="get">
            <div class="input-group">
                <input type="text" name="kw" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}" placeholder="식당 이름, 위치, 메뉴를 넣고 검색해보세요!">
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">찾기</button>
                </div>
            </div>
        </form>
    </div>

    <table class="table">
        <thead>
            <tr class="table-dark">
                <th>식당</th>
                <th>분류</th>
                <th>거리</th>
                <th>위치</th>
                <th>가격대</th>
                <th>메뉴</th>
            </tr>
        </thead>
        <tbody>
            {% for item in menu_list %}
            <tr>
                <td><a href="{% url 'pybo:detail' item.id %}">{{ item.name }}</a></td>
                <td>{{ item.type }}</td>
                <td>{{ item.distance }}</td>
                <td>{{ item.location }}</td>
                <td>{{ item.price|intcomma }}</td>
                <td>{{ item.menu_detail }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

{% block script %}
{% endblock %}

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>



{% endblock %}

templates/pybo/question_list.html
{% extends 'base.html' %}
{% block content %}


<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if question_list %}
        {% for question in question_list %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>
                <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
            </td>
            <td>{{ question.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>

{% endblock %}

<!--{% if question_list %}-->
<!--    <ul>-->
<!--    {% for question in question_list %}-->
<!--        <li><a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a></li>-->
<!--    {% endfor %}-->
<!--    </ul>-->
<!--{% else %}-->
<!--    <p>질문이 없습니다.</p>-->
<!--{% endif %}-->

templates/pybo/random.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block content %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<style>
    .form-container {
        display: flex;
        justify-content: start;
        margin-bottom: 20px;
    }
    .form-group {
        margin-right: 50px;
    }
    .form-group > label {
        font-weight: bold;
        margin-bottom: 10px;
        display: block;
    }
    .radio-group {
        display: flex;
        flex-direction: column;
    }
    .radio-group label {
        margin-bottom: 5px;
    }
</style>

<div class="container mt-4">
    <h1 class="border-bottom py-2">오눌의 점메추</h1>

    <form method="get" class="mb-3">
        <div class="form-container">
            {% for field in form %}
            <div class="form-group">
                <label>{{ field.label }}</label>
                <div class="radio-group">
                    {% for radio in field %}
                        <label>
                            {{ radio.tag }}
                            {{ radio.choice_label }}
                        </label>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        <button type="submit" class="btn btn-primary">랜덤 메뉴 추천</button>
    </form>

    <div class="card mt-3">
        <div class="card-body">
            {% if random_menu %}
                <h2 class="card-title">{{ random_menu.name }}</h2>
                <p class="card-text"><strong>종류:</strong> {{ random_menu.type }}</p>
                <p class="card-text"><strong>거리:</strong> {{ random_menu.distance }}</p>
                <p class="card-text"><strong>위치:</strong> {{ random_menu.location }}</p>
                <p class="card-text"><strong>가격:</strong> {{ random_menu.price|intcomma }}원</p>
                <p class="card-text">{{ random_menu.menu_detail }}</p>

                {% if naver_search_url %}
                <a href="{{ naver_search_url }}" class="btn btn-success" target="_blank">네이버에서 식당 검색</a>
                {% endif %}

            {% else %}
                <p class="card-text">메뉴를 선택해주세요.</p>
            {% endif %}
        </div>
    </div>
    <p>
        <div class="d-flex justify-content-start">
           <p class="card-text me-2">
               <a href="{% url 'pybo:index' %}" class="btn btn-secondary">리스트로</a>
            </p>

            <p class="card-text me-2">
            <a href="{% url 'pybo:gia' %}" class="btn btn-secondary">그냥지하에서먹자</a>
            </p>
            </p>
        </div>


</div>
{% endblock %}